language: elixir

elixir:
  - 1.1.1
  - 1.2.4

otp_release:
  - 17.4
  - 18.2

before_install:
  - sudo apt-get update -qq

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
